version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "9999:3000"
    depends_on:
      - db
  test_web:
    build: .
    command: bundle exec rake spec
    volumes:
      - .:/app
    depends_on:
      - db
